### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by ncanibano** [nscala-money/nscala-money#3]
Hi team! Are you planning to release a version with Scala 2.12 support anytime soon? Thanks a lot for your work!

**Comment by drbild** [comment]
Will look at this soon.  Just need to cross-build `core` for 2.12, without cross-building `play-json`, since Play JSON isn't published for 2.12 yet.

**Comment by ncanibano** [comment]
That will be awesome! Thanks a lot.

**Comment by ncanibano** [comment]
Tx!

**Comment by drbild** [comment]
Hmm, doesn't seem to have actually released the 2.12 build to maven central.  I'll have to look into this.

**Comment by drbild** [comment]
Now `core` is actually published for scala 2.12.  Should hit Maven Central in the next few hours.
