### ISSUE TITLE
nscala-money-play-json Scala 2.12 support

### ISSUE THREAD

**Issue by solicode** [nscala-money/nscala-money#7]
I see that 2.12 was published for `nscala-money`, but `nscala-money-play-json` [seems to be missing](http://repo1.maven.org/maven2/com/github/nscala-money/). Would it be possible to get that published as well?

If there are TODOs or something blocking it that I'm not aware of, I wouldn't mind taking a look at it.

**Comment by drbild** [comment]
Just published version `0.13.0` to support `play-json` 2.6 on `scala` 2.12.  Should it Maven Central within the hour. Hadn't released it before, because `play-json` hadn't been published for `scala` 2.12 until recently.
